import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google";
import "./globals.css";
import { DiscordProvider } from "@/contexts/DiscordContext";

const robotoFlex = Roboto_Flex({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          httpEquiv="Content-Security-Policy"
          content="default-src 'self'; connect-src 'self' wss://*.discordsays.com ws://*.discordsays.com https://*.discordsays.com http://*.discordsays.com https://discord.com; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' https://cdn.discordapp.com data:;"
        />
      </head>
      <body
        className={`${robotoFlex.className} antialiased bg-gradient-to-br from-slate-900 to-slate-800 tracking-tight`}
      >
        <DiscordProvider clientId={process.env.NEXT_PUBLIC_DISCORD_CLIENT_ID!}>
          {children}
        </DiscordProvider>
      </body>
    </html>
  );
}
